name: html
icon: html
title: HTML

services:
- name: nginx
  title: Nginx
  service: nginx
  required: true
  containers:
  - name: nginx
    env:
    - name: NGINX_VHOST_PRESET
      value: html

- name: httpd
  title: Apache HTTP server
  disabled: true  
  service: httpd
  containers:
  - name: nginx
    env:
    - name: APACHE_VHOST_PRESET
      value: html
  
